name: Governance Demo

on:
  push:
    branches:
      - main

jobs:
    telemetry:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.12'

        - name: Install dependencies
          run: |
            pip install -r requirements.txt

        - name: Emit telemetry event
          run: |
            python telemetry/emitter.py sc.pipeline.started 
            #this will emit a telemetry event indicating that the pipeline has started. You can replace "sc.pipeline.started" with any other event name that you want to emit.
            
        - name: Pipeline completed
          if: always()
          run: |
            python telemetry/emitter.py sc.pipeline.completed 
            #this will emit a telemetry event indicating that the pipeline has completed. You can replace "sc.pipeline.completed" with any other event name that you want to emit.

#test the emitter through automatic workflow runs